/* config.c generated by valac 0.28.1, the Vala compiler
 * generated from config.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <libxml/tree.h>
#include <libxml/parser.h>
#include <libxml/xpath.h>
#include <stdlib.h>
#include <string.h>
#include <gobject/gvaluecollector.h>


#define TYPE_CONFIG_XML (config_xml_get_type ())
#define CONFIG_XML(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CONFIG_XML, ConfigXML))
#define CONFIG_XML_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CONFIG_XML, ConfigXMLClass))
#define IS_CONFIG_XML(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CONFIG_XML))
#define IS_CONFIG_XML_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CONFIG_XML))
#define CONFIG_XML_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CONFIG_XML, ConfigXMLClass))

typedef struct _ConfigXML ConfigXML;
typedef struct _ConfigXMLClass ConfigXMLClass;
typedef struct _ConfigXMLPrivate ConfigXMLPrivate;
#define _xmlXPathFreeContext0(var) ((var == NULL) ? NULL : (var = (xmlXPathFreeContext (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _ParamSpecConfigXML ParamSpecConfigXML;

struct _ConfigXML {
	GTypeInstance parent_instance;
	volatile int ref_count;
	ConfigXMLPrivate * priv;
};

struct _ConfigXMLClass {
	GTypeClass parent_class;
	void (*finalize) (ConfigXML *self);
};

struct _ConfigXMLPrivate {
	xmlDoc* doc;
	xmlXPathObject* obj;
	xmlXPathContext* ctx;
	gchar* _content;
	gchar* _directory;
	gchar* _title;
	gint _height;
	gint _width;
	gboolean _enable_seed;
	gchar* _nodejs_app;
};

struct _ParamSpecConfigXML {
	GParamSpec parent_instance;
};


static gpointer config_xml_parent_class = NULL;

gpointer config_xml_ref (gpointer instance);
void config_xml_unref (gpointer instance);
GParamSpec* param_spec_config_xml (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_config_xml (GValue* value, gpointer v_object);
void value_take_config_xml (GValue* value, gpointer v_object);
gpointer value_get_config_xml (const GValue* value);
GType config_xml_get_type (void) G_GNUC_CONST;
#define CONFIG_XML_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_CONFIG_XML, ConfigXMLPrivate))
enum  {
	CONFIG_XML_DUMMY_PROPERTY
};
ConfigXML* config_xml_new (const gchar* path);
ConfigXML* config_xml_construct (GType object_type, const gchar* path);
static void config_xml_cleanup (ConfigXML* self);
static gchar* config_xml_get_string_from_attribute (ConfigXML* self, const gchar* path, const gchar* attribute);
static void config_xml_set_content (ConfigXML* self, const gchar* value);
static void config_xml_set_directory (ConfigXML* self, const gchar* value);
static gchar** config_xml_get_string_from_path (ConfigXML* self, const gchar* path, int* result_length1);
static void config_xml_set_title (ConfigXML* self, const gchar* value);
static void config_xml_set_width (ConfigXML* self, gint value);
static void config_xml_set_height (ConfigXML* self, gint value);
static gchar* config_xml_get_string_from_preference (ConfigXML* self, const gchar* name);
static void config_xml_set_enable_seed (ConfigXML* self, gboolean value);
static void config_xml_set_nodejs_app (ConfigXML* self, const gchar* value);
static void _vala_array_add1 (gchar*** array, int* length, int* size, gchar* value);
const gchar* config_xml_get_content (ConfigXML* self);
const gchar* config_xml_get_directory (ConfigXML* self);
const gchar* config_xml_get_title (ConfigXML* self);
gint config_xml_get_height (ConfigXML* self);
gint config_xml_get_width (ConfigXML* self);
gboolean config_xml_get_enable_seed (ConfigXML* self);
const gchar* config_xml_get_nodejs_app (ConfigXML* self);
static void config_xml_finalize (ConfigXML* obj);
static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func);
static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func);


ConfigXML* config_xml_construct (GType object_type, const gchar* path) {
	ConfigXML* self = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	xmlDoc* _tmp3_ = NULL;
	xmlDoc* _tmp4_ = NULL;
	xmlDoc* _tmp5_ = NULL;
	xmlXPathContext* _tmp6_ = NULL;
	xmlXPathContext* _tmp7_ = NULL;
	xmlXPathContext* _tmp8_ = NULL;
	gchar* _tmp9_ = NULL;
	gchar* _tmp10_ = NULL;
	const gchar* _tmp11_ = NULL;
	gchar** t = NULL;
	gint _tmp12_ = 0;
	gchar** _tmp13_ = NULL;
	gint t_length1 = 0;
	gint _t_size_ = 0;
	gchar** _tmp14_ = NULL;
	gint _tmp14__length1 = 0;
	gchar* w = NULL;
	gchar* _tmp17_ = NULL;
	const gchar* _tmp18_ = NULL;
	gchar* _tmp21_ = NULL;
	const gchar* _tmp22_ = NULL;
	gchar* _tmp25_ = NULL;
	const gchar* _tmp26_ = NULL;
	gchar* _tmp27_ = NULL;
	gchar* _tmp28_ = NULL;
	g_return_val_if_fail (path != NULL, NULL);
	self = (ConfigXML*) g_type_create_instance (object_type);
	xmlInitParser ();
	_tmp0_ = path;
	_tmp1_ = g_strconcat (_tmp0_, "/config.xml", NULL);
	_tmp2_ = _tmp1_;
	_tmp3_ = xmlParseFile (_tmp2_);
	self->priv->doc = _tmp3_;
	_g_free0 (_tmp2_);
	_tmp4_ = self->priv->doc;
	if (_tmp4_ == NULL) {
		return self;
	}
	_tmp5_ = self->priv->doc;
	_tmp6_ = xmlXPathNewContext (_tmp5_);
	_xmlXPathFreeContext0 (self->priv->ctx);
	self->priv->ctx = _tmp6_;
	_tmp7_ = self->priv->ctx;
	if (_tmp7_ == NULL) {
		config_xml_cleanup (self);
		return self;
	}
	_tmp8_ = self->priv->ctx;
	xmlXPathRegisterNs (_tmp8_, (xmlChar*) "x", (xmlChar*) "http://www.w3.org/ns/widgets");
	_tmp9_ = config_xml_get_string_from_attribute (self, "/x:widget/x:content", "src");
	_tmp10_ = _tmp9_;
	config_xml_set_content (self, _tmp10_);
	_g_free0 (_tmp10_);
	_tmp11_ = path;
	config_xml_set_directory (self, _tmp11_);
	_tmp13_ = config_xml_get_string_from_path (self, "/x:widget/x:name", &_tmp12_);
	t = _tmp13_;
	t_length1 = _tmp12_;
	_t_size_ = t_length1;
	_tmp14_ = t;
	_tmp14__length1 = t_length1;
	if (_tmp14__length1 > 0) {
		gchar** _tmp15_ = NULL;
		gint _tmp15__length1 = 0;
		const gchar* _tmp16_ = NULL;
		_tmp15_ = t;
		_tmp15__length1 = t_length1;
		_tmp16_ = _tmp15_[0];
		config_xml_set_title (self, _tmp16_);
	}
	_tmp17_ = config_xml_get_string_from_attribute (self, "/x:widget", "width");
	w = _tmp17_;
	_tmp18_ = w;
	if (_tmp18_ != NULL) {
		const gchar* _tmp19_ = NULL;
		gint _tmp20_ = 0;
		_tmp19_ = w;
		_tmp20_ = atoi (_tmp19_);
		config_xml_set_width (self, _tmp20_);
	}
	_tmp21_ = config_xml_get_string_from_attribute (self, "/x:widget", "height");
	_g_free0 (w);
	w = _tmp21_;
	_tmp22_ = w;
	if (_tmp22_ != NULL) {
		const gchar* _tmp23_ = NULL;
		gint _tmp24_ = 0;
		_tmp23_ = w;
		_tmp24_ = atoi (_tmp23_);
		config_xml_set_height (self, _tmp24_);
	}
	_tmp25_ = config_xml_get_string_from_preference (self, "enable-seed");
	_g_free0 (w);
	w = _tmp25_;
	_tmp26_ = w;
	if (g_strcmp0 (_tmp26_, "false") == 0) {
		config_xml_set_enable_seed (self, FALSE);
	}
	_tmp27_ = config_xml_get_string_from_preference (self, "nodejs-app");
	_tmp28_ = _tmp27_;
	config_xml_set_nodejs_app (self, _tmp28_);
	_g_free0 (_tmp28_);
	config_xml_cleanup (self);
	_g_free0 (w);
	t = (_vala_array_free (t, t_length1, (GDestroyNotify) g_free), NULL);
	return self;
}


ConfigXML* config_xml_new (const gchar* path) {
	return config_xml_construct (TYPE_CONFIG_XML, path);
}


static void _vala_array_add1 (gchar*** array, int* length, int* size, gchar* value) {
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}


static gchar** config_xml_get_string_from_path (ConfigXML* self, const gchar* path, int* result_length1) {
	gchar** result = NULL;
	gchar** return_values = NULL;
	gchar** _tmp0_ = NULL;
	gint return_values_length1 = 0;
	gint _return_values_size_ = 0;
	xmlXPathContext* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	xmlXPathObject* _tmp3_ = NULL;
	gboolean _tmp4_ = FALSE;
	xmlXPathObject* _tmp5_ = NULL;
	gchar** _tmp22_ = NULL;
	gint _tmp22__length1 = 0;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (path != NULL, NULL);
	_tmp0_ = g_new0 (gchar*, 0 + 1);
	return_values = _tmp0_;
	return_values_length1 = 0;
	_return_values_size_ = return_values_length1;
	_tmp1_ = self->priv->ctx;
	_tmp2_ = path;
	_tmp3_ = xmlXPathEvalExpression ((xmlChar*) _tmp2_, _tmp1_);
	self->priv->obj = _tmp3_;
	_tmp5_ = self->priv->obj;
	if (_tmp5_ == NULL) {
		_tmp4_ = TRUE;
	} else {
		xmlXPathObject* _tmp6_ = NULL;
		xmlNodeSet* _tmp7_ = NULL;
		_tmp6_ = self->priv->obj;
		_tmp7_ = _tmp6_->nodesetval;
		_tmp4_ = _tmp7_ == NULL;
	}
	if (_tmp4_) {
		gchar** _tmp8_ = NULL;
		gint _tmp8__length1 = 0;
		config_xml_cleanup (self);
		_tmp8_ = return_values;
		_tmp8__length1 = return_values_length1;
		if (result_length1) {
			*result_length1 = _tmp8__length1;
		}
		result = _tmp8_;
		return result;
	}
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp9_ = FALSE;
			_tmp9_ = TRUE;
			while (TRUE) {
				gint _tmp11_ = 0;
				xmlXPathObject* _tmp12_ = NULL;
				xmlNodeSet* _tmp13_ = NULL;
				gint _tmp14_ = 0;
				xmlNode* node = NULL;
				xmlXPathObject* _tmp15_ = NULL;
				xmlNodeSet* _tmp16_ = NULL;
				gint _tmp17_ = 0;
				xmlNode* _tmp18_ = NULL;
				gchar** _tmp19_ = NULL;
				gint _tmp19__length1 = 0;
				xmlNode* _tmp20_ = NULL;
				gchar* _tmp21_ = NULL;
				if (!_tmp9_) {
					gint _tmp10_ = 0;
					_tmp10_ = i;
					i = _tmp10_ + 1;
				}
				_tmp9_ = FALSE;
				_tmp11_ = i;
				_tmp12_ = self->priv->obj;
				_tmp13_ = _tmp12_->nodesetval;
				_tmp14_ = xmlXPathNodeSetGetLength (_tmp13_);
				if (!(_tmp11_ < _tmp14_)) {
					break;
				}
				_tmp15_ = self->priv->obj;
				_tmp16_ = _tmp15_->nodesetval;
				_tmp17_ = i;
				_tmp18_ = xmlXPathNodeSetItem (_tmp16_, _tmp17_);
				node = _tmp18_;
				_tmp19_ = return_values;
				_tmp19__length1 = return_values_length1;
				_tmp20_ = node;
				_tmp21_ = (gchar*) xmlNodeGetContent (_tmp20_);
				_vala_array_add1 (&return_values, &return_values_length1, &_return_values_size_, _tmp21_);
			}
		}
	}
	_tmp22_ = return_values;
	_tmp22__length1 = return_values_length1;
	if (result_length1) {
		*result_length1 = _tmp22__length1;
	}
	result = _tmp22_;
	return result;
}


static gchar* config_xml_get_string_from_attribute (ConfigXML* self, const gchar* path, const gchar* attribute) {
	gchar* result = NULL;
	gchar* return_value = NULL;
	xmlXPathContext* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	xmlXPathObject* _tmp2_ = NULL;
	gboolean _tmp3_ = FALSE;
	xmlXPathObject* _tmp4_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (path != NULL, NULL);
	g_return_val_if_fail (attribute != NULL, NULL);
	return_value = NULL;
	_tmp0_ = self->priv->ctx;
	_tmp1_ = path;
	_tmp2_ = xmlXPathEvalExpression ((xmlChar*) _tmp1_, _tmp0_);
	self->priv->obj = _tmp2_;
	_tmp4_ = self->priv->obj;
	if (_tmp4_ == NULL) {
		_tmp3_ = TRUE;
	} else {
		xmlXPathObject* _tmp5_ = NULL;
		xmlNodeSet* _tmp6_ = NULL;
		_tmp5_ = self->priv->obj;
		_tmp6_ = _tmp5_->nodesetval;
		_tmp3_ = _tmp6_ == NULL;
	}
	if (_tmp3_) {
		config_xml_cleanup (self);
		result = return_value;
		return result;
	}
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp7_ = FALSE;
			_tmp7_ = TRUE;
			while (TRUE) {
				gint _tmp9_ = 0;
				xmlXPathObject* _tmp10_ = NULL;
				xmlNodeSet* _tmp11_ = NULL;
				gint _tmp12_ = 0;
				xmlNode* node = NULL;
				xmlXPathObject* _tmp13_ = NULL;
				xmlNodeSet* _tmp14_ = NULL;
				gint _tmp15_ = 0;
				xmlNode* _tmp16_ = NULL;
				xmlAttr* attr = NULL;
				xmlNode* _tmp17_ = NULL;
				xmlAttr* _tmp18_ = NULL;
				if (!_tmp7_) {
					gint _tmp8_ = 0;
					_tmp8_ = i;
					i = _tmp8_ + 1;
				}
				_tmp7_ = FALSE;
				_tmp9_ = i;
				_tmp10_ = self->priv->obj;
				_tmp11_ = _tmp10_->nodesetval;
				_tmp12_ = xmlXPathNodeSetGetLength (_tmp11_);
				if (!(_tmp9_ < _tmp12_)) {
					break;
				}
				_tmp13_ = self->priv->obj;
				_tmp14_ = _tmp13_->nodesetval;
				_tmp15_ = i;
				_tmp16_ = xmlXPathNodeSetItem (_tmp14_, _tmp15_);
				node = _tmp16_;
				attr = NULL;
				_tmp17_ = node;
				_tmp18_ = _tmp17_->properties;
				attr = _tmp18_;
				while (TRUE) {
					xmlAttr* _tmp19_ = NULL;
					xmlAttr* _tmp20_ = NULL;
					const gchar* _tmp21_ = NULL;
					const gchar* _tmp22_ = NULL;
					xmlAttr* _tmp27_ = NULL;
					xmlAttr* _tmp28_ = NULL;
					_tmp19_ = attr;
					if (!(_tmp19_ != NULL)) {
						break;
					}
					_tmp20_ = attr;
					_tmp21_ = _tmp20_->name;
					_tmp22_ = attribute;
					if (g_strcmp0 (_tmp21_, _tmp22_) == 0) {
						xmlAttr* _tmp23_ = NULL;
						xmlNode* _tmp24_ = NULL;
						const gchar* _tmp25_ = NULL;
						gchar* _tmp26_ = NULL;
						_tmp23_ = attr;
						_tmp24_ = _tmp23_->children;
						_tmp25_ = _tmp24_->content;
						_tmp26_ = g_strconcat (_tmp25_, "", NULL);
						_g_free0 (return_value);
						return_value = _tmp26_;
						break;
					}
					_tmp27_ = attr;
					_tmp28_ = _tmp27_->next;
					attr = _tmp28_;
				}
			}
		}
	}
	result = return_value;
	return result;
}


static gchar* config_xml_get_string_from_preference (ConfigXML* self, const gchar* name) {
	gchar* result = NULL;
	gchar* return_value = NULL;
	xmlXPathContext* _tmp0_ = NULL;
	xmlXPathObject* _tmp1_ = NULL;
	gboolean _tmp2_ = FALSE;
	xmlXPathObject* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (name != NULL, NULL);
	return_value = NULL;
	_tmp0_ = self->priv->ctx;
	_tmp1_ = xmlXPathEvalExpression ((xmlChar*) "/x:widget/x:preference", _tmp0_);
	self->priv->obj = _tmp1_;
	_tmp3_ = self->priv->obj;
	if (_tmp3_ == NULL) {
		_tmp2_ = TRUE;
	} else {
		xmlXPathObject* _tmp4_ = NULL;
		xmlNodeSet* _tmp5_ = NULL;
		_tmp4_ = self->priv->obj;
		_tmp5_ = _tmp4_->nodesetval;
		_tmp2_ = _tmp5_ == NULL;
	}
	if (_tmp2_) {
		config_xml_cleanup (self);
		result = return_value;
		return result;
	}
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp6_ = FALSE;
			_tmp6_ = TRUE;
			while (TRUE) {
				gint _tmp8_ = 0;
				xmlXPathObject* _tmp9_ = NULL;
				xmlNodeSet* _tmp10_ = NULL;
				gint _tmp11_ = 0;
				xmlNode* node = NULL;
				xmlXPathObject* _tmp12_ = NULL;
				xmlNodeSet* _tmp13_ = NULL;
				gint _tmp14_ = 0;
				xmlNode* _tmp15_ = NULL;
				xmlAttr* attr = NULL;
				xmlNode* _tmp16_ = NULL;
				xmlAttr* _tmp17_ = NULL;
				gboolean pickupNow = FALSE;
				if (!_tmp6_) {
					gint _tmp7_ = 0;
					_tmp7_ = i;
					i = _tmp7_ + 1;
				}
				_tmp6_ = FALSE;
				_tmp8_ = i;
				_tmp9_ = self->priv->obj;
				_tmp10_ = _tmp9_->nodesetval;
				_tmp11_ = xmlXPathNodeSetGetLength (_tmp10_);
				if (!(_tmp8_ < _tmp11_)) {
					break;
				}
				_tmp12_ = self->priv->obj;
				_tmp13_ = _tmp12_->nodesetval;
				_tmp14_ = i;
				_tmp15_ = xmlXPathNodeSetItem (_tmp13_, _tmp14_);
				node = _tmp15_;
				attr = NULL;
				_tmp16_ = node;
				_tmp17_ = _tmp16_->properties;
				attr = _tmp17_;
				pickupNow = FALSE;
				while (TRUE) {
					xmlAttr* _tmp18_ = NULL;
					xmlAttr* _tmp19_ = NULL;
					const gchar* _tmp20_ = NULL;
					gboolean _tmp25_ = FALSE;
					xmlAttr* _tmp26_ = NULL;
					const gchar* _tmp27_ = NULL;
					xmlAttr* _tmp33_ = NULL;
					xmlAttr* _tmp34_ = NULL;
					_tmp18_ = attr;
					if (!(_tmp18_ != NULL)) {
						break;
					}
					_tmp19_ = attr;
					_tmp20_ = _tmp19_->name;
					if (g_strcmp0 (_tmp20_, "name") == 0) {
						xmlAttr* _tmp21_ = NULL;
						xmlNode* _tmp22_ = NULL;
						const gchar* _tmp23_ = NULL;
						const gchar* _tmp24_ = NULL;
						pickupNow = FALSE;
						_tmp21_ = attr;
						_tmp22_ = _tmp21_->children;
						_tmp23_ = _tmp22_->content;
						_tmp24_ = name;
						if (g_strcmp0 (_tmp23_, _tmp24_) == 0) {
							pickupNow = TRUE;
						}
					}
					_tmp26_ = attr;
					_tmp27_ = _tmp26_->name;
					if (g_strcmp0 (_tmp27_, "value") == 0) {
						gboolean _tmp28_ = FALSE;
						_tmp28_ = pickupNow;
						_tmp25_ = _tmp28_;
					} else {
						_tmp25_ = FALSE;
					}
					if (_tmp25_) {
						xmlAttr* _tmp29_ = NULL;
						xmlNode* _tmp30_ = NULL;
						const gchar* _tmp31_ = NULL;
						gchar* _tmp32_ = NULL;
						_tmp29_ = attr;
						_tmp30_ = _tmp29_->children;
						_tmp31_ = _tmp30_->content;
						_tmp32_ = g_strconcat (_tmp31_, "", NULL);
						_g_free0 (return_value);
						return_value = _tmp32_;
						break;
					}
					_tmp33_ = attr;
					_tmp34_ = _tmp33_->next;
					attr = _tmp34_;
				}
			}
		}
	}
	result = return_value;
	return result;
}


static void config_xml_cleanup (ConfigXML* self) {
	xmlXPathObject* _tmp0_ = NULL;
	xmlDoc* _tmp2_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->obj;
	if (_tmp0_ != NULL) {
		xmlXPathObject* _tmp1_ = NULL;
		_tmp1_ = self->priv->obj;
		xmlXPathFreeObject (_tmp1_);
	}
	_tmp2_ = self->priv->doc;
	if (_tmp2_ != NULL) {
		xmlDoc* _tmp3_ = NULL;
		_tmp3_ = self->priv->doc;
		xmlFreeDoc (_tmp3_);
	}
}


const gchar* config_xml_get_content (ConfigXML* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_content;
	result = _tmp0_;
	return result;
}


static void config_xml_set_content (ConfigXML* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_content);
	self->priv->_content = _tmp1_;
}


const gchar* config_xml_get_directory (ConfigXML* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_directory;
	result = _tmp0_;
	return result;
}


static void config_xml_set_directory (ConfigXML* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_directory);
	self->priv->_directory = _tmp1_;
}


const gchar* config_xml_get_title (ConfigXML* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_title;
	result = _tmp0_;
	return result;
}


static void config_xml_set_title (ConfigXML* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_title);
	self->priv->_title = _tmp1_;
}


gint config_xml_get_height (ConfigXML* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_height;
	result = _tmp0_;
	return result;
}


static void config_xml_set_height (ConfigXML* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_height = _tmp0_;
}


gint config_xml_get_width (ConfigXML* self) {
	gint result;
	gint _tmp0_ = 0;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_width;
	result = _tmp0_;
	return result;
}


static void config_xml_set_width (ConfigXML* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_width = _tmp0_;
}


gboolean config_xml_get_enable_seed (ConfigXML* self) {
	gboolean result;
	gboolean _tmp0_ = FALSE;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_enable_seed;
	result = _tmp0_;
	return result;
}


static void config_xml_set_enable_seed (ConfigXML* self, gboolean value) {
	gboolean _tmp0_ = FALSE;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_enable_seed = _tmp0_;
}


const gchar* config_xml_get_nodejs_app (ConfigXML* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_nodejs_app;
	result = _tmp0_;
	return result;
}


static void config_xml_set_nodejs_app (ConfigXML* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_nodejs_app);
	self->priv->_nodejs_app = _tmp1_;
}


static void value_config_xml_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void value_config_xml_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		config_xml_unref (value->data[0].v_pointer);
	}
}


static void value_config_xml_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = config_xml_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer value_config_xml_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* value_config_xml_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		ConfigXML* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = config_xml_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* value_config_xml_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	ConfigXML** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = config_xml_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* param_spec_config_xml (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	ParamSpecConfigXML* spec;
	g_return_val_if_fail (g_type_is_a (object_type, TYPE_CONFIG_XML), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer value_get_config_xml (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_CONFIG_XML), NULL);
	return value->data[0].v_pointer;
}


void value_set_config_xml (GValue* value, gpointer v_object) {
	ConfigXML* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_CONFIG_XML));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_CONFIG_XML));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		config_xml_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		config_xml_unref (old);
	}
}


void value_take_config_xml (GValue* value, gpointer v_object) {
	ConfigXML* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, TYPE_CONFIG_XML));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, TYPE_CONFIG_XML));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		config_xml_unref (old);
	}
}


static void config_xml_class_init (ConfigXMLClass * klass) {
	config_xml_parent_class = g_type_class_peek_parent (klass);
	((ConfigXMLClass *) klass)->finalize = config_xml_finalize;
	g_type_class_add_private (klass, sizeof (ConfigXMLPrivate));
}


static void config_xml_instance_init (ConfigXML * self) {
	self->priv = CONFIG_XML_GET_PRIVATE (self);
	self->priv->doc = NULL;
	self->priv->obj = NULL;
	self->priv->ctx = NULL;
	self->priv->_content = NULL;
	self->priv->_directory = NULL;
	self->priv->_title = NULL;
	self->priv->_height = -1;
	self->priv->_width = -1;
	self->priv->_enable_seed = TRUE;
	self->priv->_nodejs_app = NULL;
	self->ref_count = 1;
}


static void config_xml_finalize (ConfigXML* obj) {
	ConfigXML * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_CONFIG_XML, ConfigXML);
	g_signal_handlers_destroy (self);
	_xmlXPathFreeContext0 (self->priv->ctx);
	_g_free0 (self->priv->_content);
	_g_free0 (self->priv->_directory);
	_g_free0 (self->priv->_title);
	_g_free0 (self->priv->_nodejs_app);
}


GType config_xml_get_type (void) {
	static volatile gsize config_xml_type_id__volatile = 0;
	if (g_once_init_enter (&config_xml_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { value_config_xml_init, value_config_xml_free_value, value_config_xml_copy_value, value_config_xml_peek_pointer, "p", value_config_xml_collect_value, "p", value_config_xml_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (ConfigXMLClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) config_xml_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ConfigXML), 0, (GInstanceInitFunc) config_xml_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType config_xml_type_id;
		config_xml_type_id = g_type_register_fundamental (g_type_fundamental_next (), "ConfigXML", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&config_xml_type_id__volatile, config_xml_type_id);
	}
	return config_xml_type_id__volatile;
}


gpointer config_xml_ref (gpointer instance) {
	ConfigXML* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void config_xml_unref (gpointer instance) {
	ConfigXML* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		CONFIG_XML_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}


static void _vala_array_destroy (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	if ((array != NULL) && (destroy_func != NULL)) {
		int i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}


static void _vala_array_free (gpointer array, gint array_length, GDestroyNotify destroy_func) {
	_vala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}



