/* webview.c generated by valac 0.28.1, the Vala compiler
 * generated from webview.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <webkit/webkit.h>
#include <seed.h>


#define TYPE_WEB_VIEW (web_view_get_type ())
#define WEB_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_WEB_VIEW, WebView))
#define WEB_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_WEB_VIEW, WebViewClass))
#define IS_WEB_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_WEB_VIEW))
#define IS_WEB_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_WEB_VIEW))
#define WEB_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_WEB_VIEW, WebViewClass))

typedef struct _WebView WebView;
typedef struct _WebViewClass WebViewClass;
typedef struct _WebViewPrivate WebViewPrivate;

#define TYPE_CONFIG_XML (config_xml_get_type ())
#define CONFIG_XML(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CONFIG_XML, ConfigXML))
#define CONFIG_XML_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CONFIG_XML, ConfigXMLClass))
#define IS_CONFIG_XML(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CONFIG_XML))
#define IS_CONFIG_XML_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CONFIG_XML))
#define CONFIG_XML_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CONFIG_XML, ConfigXMLClass))

typedef struct _ConfigXML ConfigXML;
typedef struct _ConfigXMLClass ConfigXMLClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _WebView {
	WebKitWebView parent_instance;
	WebViewPrivate * priv;
};

struct _WebViewClass {
	WebKitWebViewClass parent_class;
};

struct _WebViewPrivate {
	SeedEngine* engine;
};


static gpointer web_view_parent_class = NULL;

GType web_view_get_type (void) G_GNUC_CONST;
#define WEB_VIEW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_WEB_VIEW, WebViewPrivate))
enum  {
	WEB_VIEW_DUMMY_PROPERTY
};
gpointer config_xml_ref (gpointer instance);
void config_xml_unref (gpointer instance);
GParamSpec* param_spec_config_xml (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_config_xml (GValue* value, gpointer v_object);
void value_take_config_xml (GValue* value, gpointer v_object);
gpointer value_get_config_xml (const GValue* value);
GType config_xml_get_type (void) G_GNUC_CONST;
WebView* web_view_new (ConfigXML* config);
WebView* web_view_construct (GType object_type, ConfigXML* config);
gboolean config_xml_get_enable_seed (ConfigXML* self);
static void ___lambda4_ (WebView* self, WebKitWebFrame* frame, void* context);
static void ____lambda4__webkit_web_view_window_object_cleared (WebKitWebView* _sender, WebKitWebFrame* frame, void* context, void* window_object, gpointer self);
static void web_view_finalize (GObject* obj);


static void ___lambda4_ (WebView* self, WebKitWebFrame* frame, void* context) {
	SeedGlobalContext* c = NULL;
	WebKitWebFrame* _tmp0_ = NULL;
	void* _tmp1_ = NULL;
	SeedEngine* _tmp2_ = NULL;
	g_return_if_fail (frame != NULL);
	_tmp0_ = frame;
	_tmp1_ = webkit_web_frame_get_global_context (_tmp0_);
	c = (SeedGlobalContext*) _tmp1_;
	_tmp2_ = seed_init_with_context (0, NULL, c);
	self->priv->engine = _tmp2_;
}


static void ____lambda4__webkit_web_view_window_object_cleared (WebKitWebView* _sender, WebKitWebFrame* frame, void* context, void* window_object, gpointer self) {
	___lambda4_ ((WebView*) self, frame, context);
}


WebView* web_view_construct (GType object_type, ConfigXML* config) {
	WebView * self = NULL;
	WebKitWebSettings* settings = NULL;
	WebKitWebSettings* _tmp0_ = NULL;
	WebKitWebSettings* _tmp1_ = NULL;
	WebKitWebSettings* _tmp2_ = NULL;
	WebKitWebSettings* _tmp3_ = NULL;
	WebKitWebSettings* _tmp4_ = NULL;
	ConfigXML* _tmp5_ = NULL;
	gboolean _tmp6_ = FALSE;
	gboolean _tmp7_ = FALSE;
	g_return_val_if_fail (config != NULL, NULL);
	self = (WebView*) g_object_new (object_type, NULL);
	_tmp0_ = webkit_web_settings_new ();
	settings = _tmp0_;
	_tmp1_ = settings;
	g_object_set (_tmp1_, "enable-file-access-from-file-uris", TRUE, NULL);
	_tmp2_ = settings;
	g_object_set (_tmp2_, "enable-universal-access-from-file-uris", TRUE, NULL);
	_tmp3_ = settings;
	g_object_set (_tmp3_, "javascript-can-open-windows-automatically", TRUE, NULL);
	_tmp4_ = settings;
	webkit_web_view_set_settings ((WebKitWebView*) self, _tmp4_);
	_tmp5_ = config;
	_tmp6_ = config_xml_get_enable_seed (_tmp5_);
	_tmp7_ = _tmp6_;
	if (_tmp7_) {
		g_signal_connect_object ((WebKitWebView*) self, "window-object-cleared", (GCallback) ____lambda4__webkit_web_view_window_object_cleared, self, 0);
	}
	_g_object_unref0 (settings);
	return self;
}


WebView* web_view_new (ConfigXML* config) {
	return web_view_construct (TYPE_WEB_VIEW, config);
}


static void web_view_class_init (WebViewClass * klass) {
	web_view_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (WebViewPrivate));
	G_OBJECT_CLASS (klass)->finalize = web_view_finalize;
}


static void web_view_instance_init (WebView * self) {
	self->priv = WEB_VIEW_GET_PRIVATE (self);
}


static void web_view_finalize (GObject* obj) {
	WebView * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_WEB_VIEW, WebView);
	G_OBJECT_CLASS (web_view_parent_class)->finalize (obj);
}


GType web_view_get_type (void) {
	static volatile gsize web_view_type_id__volatile = 0;
	if (g_once_init_enter (&web_view_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (WebViewClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) web_view_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (WebView), 0, (GInstanceInitFunc) web_view_instance_init, NULL };
		GType web_view_type_id;
		web_view_type_id = g_type_register_static (WEBKIT_TYPE_WEB_VIEW, "WebView", &g_define_type_info, 0);
		g_once_init_leave (&web_view_type_id__volatile, web_view_type_id);
	}
	return web_view_type_id__volatile;
}



