/* window.c generated by valac 0.28.1, the Vala compiler
 * generated from window.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <gtk/gtk.h>
#include <webkit/webkit.h>
#include <stdlib.h>
#include <string.h>


#define TYPE_APP_WINDOW (app_window_get_type ())
#define APP_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_APP_WINDOW, AppWindow))
#define APP_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_APP_WINDOW, AppWindowClass))
#define IS_APP_WINDOW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_APP_WINDOW))
#define IS_APP_WINDOW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_APP_WINDOW))
#define APP_WINDOW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_APP_WINDOW, AppWindowClass))

typedef struct _AppWindow AppWindow;
typedef struct _AppWindowClass AppWindowClass;
typedef struct _AppWindowPrivate AppWindowPrivate;

#define TYPE_CONFIG_XML (config_xml_get_type ())
#define CONFIG_XML(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_CONFIG_XML, ConfigXML))
#define CONFIG_XML_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_CONFIG_XML, ConfigXMLClass))
#define IS_CONFIG_XML(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_CONFIG_XML))
#define IS_CONFIG_XML_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_CONFIG_XML))
#define CONFIG_XML_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_CONFIG_XML, ConfigXMLClass))

typedef struct _ConfigXML ConfigXML;
typedef struct _ConfigXMLClass ConfigXMLClass;
#define _config_xml_unref0(var) ((var == NULL) ? NULL : (var = (config_xml_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define TYPE_WEB_VIEW (web_view_get_type ())
#define WEB_VIEW(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_WEB_VIEW, WebView))
#define WEB_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_WEB_VIEW, WebViewClass))
#define IS_WEB_VIEW(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_WEB_VIEW))
#define IS_WEB_VIEW_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_WEB_VIEW))
#define WEB_VIEW_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_WEB_VIEW, WebViewClass))

typedef struct _WebView WebView;
typedef struct _WebViewClass WebViewClass;
#define _g_free0(var) (var = (g_free (var), NULL))

struct _AppWindow {
	GtkWindow parent_instance;
	AppWindowPrivate * priv;
};

struct _AppWindowClass {
	GtkWindowClass parent_class;
};

struct _AppWindowPrivate {
	ConfigXML* config;
	GtkScrolledWindow* scrolledWindow;
};


static gpointer app_window_parent_class = NULL;

GType app_window_get_type (void) G_GNUC_CONST;
gpointer config_xml_ref (gpointer instance);
void config_xml_unref (gpointer instance);
GParamSpec* param_spec_config_xml (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_config_xml (GValue* value, gpointer v_object);
void value_take_config_xml (GValue* value, gpointer v_object);
gpointer value_get_config_xml (const GValue* value);
GType config_xml_get_type (void) G_GNUC_CONST;
#define APP_WINDOW_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), TYPE_APP_WINDOW, AppWindowPrivate))
enum  {
	APP_WINDOW_DUMMY_PROPERTY
};
AppWindow* app_window_new (ConfigXML* config);
AppWindow* app_window_construct (GType object_type, ConfigXML* config);
GType web_view_get_type (void) G_GNUC_CONST;
WebView* web_view_new (ConfigXML* config);
WebView* web_view_construct (GType object_type, ConfigXML* config);
const gchar* config_xml_get_directory (ConfigXML* self);
const gchar* config_xml_get_content (ConfigXML* self);
gint config_xml_get_width (ConfigXML* self);
gint config_xml_get_height (ConfigXML* self);
static void __lambda5_ (AppWindow* self);
static void ___lambda5__gtk_widget_destroy (GtkWidget* _sender, gpointer self);
static void app_window_finalize (GObject* obj);


static gpointer _config_xml_ref0 (gpointer self) {
	return self ? config_xml_ref (self) : NULL;
}


static void __lambda5_ (AppWindow* self) {
	gtk_main_quit ();
}


static void ___lambda5__gtk_widget_destroy (GtkWidget* _sender, gpointer self) {
	__lambda5_ ((AppWindow*) self);
}


AppWindow* app_window_construct (GType object_type, ConfigXML* config) {
	AppWindow * self = NULL;
	GtkScrolledWindow* _tmp0_ = NULL;
	ConfigXML* _tmp1_ = NULL;
	ConfigXML* _tmp2_ = NULL;
	WebView* w = NULL;
	ConfigXML* _tmp3_ = NULL;
	WebView* _tmp4_ = NULL;
	GtkScrolledWindow* _tmp5_ = NULL;
	GtkScrolledWindow* _tmp6_ = NULL;
	WebView* _tmp7_ = NULL;
	WebView* _tmp8_ = NULL;
	ConfigXML* _tmp9_ = NULL;
	const gchar* _tmp10_ = NULL;
	const gchar* _tmp11_ = NULL;
	gchar* _tmp12_ = NULL;
	gchar* _tmp13_ = NULL;
	gchar* _tmp14_ = NULL;
	gchar* _tmp15_ = NULL;
	ConfigXML* _tmp16_ = NULL;
	const gchar* _tmp17_ = NULL;
	const gchar* _tmp18_ = NULL;
	gchar* _tmp19_ = NULL;
	gchar* _tmp20_ = NULL;
	WebKitWebWindowFeatures* f = NULL;
	WebView* _tmp21_ = NULL;
	WebKitWebWindowFeatures* _tmp22_ = NULL;
	WebKitWebWindowFeatures* _tmp23_ = NULL;
	ConfigXML* _tmp24_ = NULL;
	gint _tmp25_ = 0;
	gint _tmp26_ = 0;
	ConfigXML* _tmp31_ = NULL;
	gint _tmp32_ = 0;
	gint _tmp33_ = 0;
	g_return_val_if_fail (config != NULL, NULL);
	self = (AppWindow*) g_object_new (object_type, NULL);
	_tmp0_ = (GtkScrolledWindow*) gtk_scrolled_window_new (NULL, NULL);
	g_object_ref_sink (_tmp0_);
	_g_object_unref0 (self->priv->scrolledWindow);
	self->priv->scrolledWindow = _tmp0_;
	_tmp1_ = config;
	_tmp2_ = _config_xml_ref0 (_tmp1_);
	_config_xml_unref0 (self->priv->config);
	self->priv->config = _tmp2_;
	_tmp3_ = config;
	_tmp4_ = web_view_new (_tmp3_);
	g_object_ref_sink (_tmp4_);
	w = _tmp4_;
	_tmp5_ = self->priv->scrolledWindow;
	gtk_container_add ((GtkContainer*) self, (GtkWidget*) _tmp5_);
	_tmp6_ = self->priv->scrolledWindow;
	_tmp7_ = w;
	gtk_container_add ((GtkContainer*) _tmp6_, (GtkWidget*) _tmp7_);
	_tmp8_ = w;
	_tmp9_ = config;
	_tmp10_ = config_xml_get_directory (_tmp9_);
	_tmp11_ = _tmp10_;
	_tmp12_ = g_strconcat ("file://", _tmp11_, NULL);
	_tmp13_ = _tmp12_;
	_tmp14_ = g_strconcat (_tmp13_, "/", NULL);
	_tmp15_ = _tmp14_;
	_tmp16_ = config;
	_tmp17_ = config_xml_get_content (_tmp16_);
	_tmp18_ = _tmp17_;
	_tmp19_ = g_strconcat (_tmp15_, _tmp18_, NULL);
	_tmp20_ = _tmp19_;
	webkit_web_view_load_uri ((WebKitWebView*) _tmp8_, _tmp20_);
	_g_free0 (_tmp20_);
	_g_free0 (_tmp15_);
	_g_free0 (_tmp13_);
	_tmp21_ = w;
	g_object_get ((WebKitWebView*) _tmp21_, "window-features", &_tmp22_, NULL);
	_tmp23_ = _tmp22_;
	f = _tmp23_;
	_tmp24_ = config;
	_tmp25_ = config_xml_get_width (_tmp24_);
	_tmp26_ = _tmp25_;
	if (_tmp26_ != (-1)) {
		WebKitWebWindowFeatures* _tmp27_ = NULL;
		ConfigXML* _tmp28_ = NULL;
		gint _tmp29_ = 0;
		gint _tmp30_ = 0;
		_tmp27_ = f;
		_tmp28_ = config;
		_tmp29_ = config_xml_get_width (_tmp28_);
		_tmp30_ = _tmp29_;
		g_object_set (_tmp27_, "width", _tmp30_, NULL);
	}
	_tmp31_ = config;
	_tmp32_ = config_xml_get_height (_tmp31_);
	_tmp33_ = _tmp32_;
	if (_tmp33_ != (-1)) {
		WebKitWebWindowFeatures* _tmp34_ = NULL;
		ConfigXML* _tmp35_ = NULL;
		gint _tmp36_ = 0;
		gint _tmp37_ = 0;
		_tmp34_ = f;
		_tmp35_ = config;
		_tmp36_ = config_xml_get_height (_tmp35_);
		_tmp37_ = _tmp36_;
		g_object_set (_tmp34_, "height", _tmp37_, NULL);
	}
	g_signal_connect_object ((GtkWidget*) self, "destroy", (GCallback) ___lambda5__gtk_widget_destroy, self, 0);
	_g_object_unref0 (f);
	_g_object_unref0 (w);
	return self;
}


AppWindow* app_window_new (ConfigXML* config) {
	return app_window_construct (TYPE_APP_WINDOW, config);
}


static void app_window_class_init (AppWindowClass * klass) {
	app_window_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (AppWindowPrivate));
	G_OBJECT_CLASS (klass)->finalize = app_window_finalize;
}


static void app_window_instance_init (AppWindow * self) {
	self->priv = APP_WINDOW_GET_PRIVATE (self);
	self->priv->config = NULL;
	self->priv->scrolledWindow = NULL;
}


static void app_window_finalize (GObject* obj) {
	AppWindow * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, TYPE_APP_WINDOW, AppWindow);
	_config_xml_unref0 (self->priv->config);
	_g_object_unref0 (self->priv->scrolledWindow);
	G_OBJECT_CLASS (app_window_parent_class)->finalize (obj);
}


GType app_window_get_type (void) {
	static volatile gsize app_window_type_id__volatile = 0;
	if (g_once_init_enter (&app_window_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (AppWindowClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) app_window_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (AppWindow), 0, (GInstanceInitFunc) app_window_instance_init, NULL };
		GType app_window_type_id;
		app_window_type_id = g_type_register_static (gtk_window_get_type (), "AppWindow", &g_define_type_info, 0);
		g_once_init_leave (&app_window_type_id__volatile, app_window_type_id);
	}
	return app_window_type_id__volatile;
}



